### ISSUE TITLE
Error: AssertionError [ERR_ASSERTION]: 400 != 400

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty-puppet-wechat4u#3]
```
02:37:10 SILL StateSwitch <PuppetWechat4u> off() is false
02:37:35 VERB PuppetWechat4u monkeyPatchOffState(checkLogin) funcNew()
02:37:35 SILL StateSwitch <PuppetWechat4u> off() is false
Bot error: Error: AssertionError [ERR_ASSERTION]: 400 != 400
    at PuppetWechat4u.puppet.on.error (/home/zixia/chatie/wechaty/src/wechaty.ts:586:32)
    at PuppetWechat4u.emit (events.js:182:13)
    at PuppetWechat4u.EventEmitter.emit (domain.js:442:20)
    at PuppetWechat4u.emit (/home/zixia/chatie/wechaty/node_modules/wechaty-puppet/src/puppet.ts:258:18)
    at Wechat.wechat4u.on (/home/zixia/chatie/wechaty/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:303:12)
    at Wechat.emit (events.js:182:13)
    at Wechat.EventEmitter.emit (domain.js:442:20)
    at /home/zixia/chatie/wechaty/node_modules/wechat4u/src/wechat.js:200:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
02:37:35 VERB MemoryCard delete(PUPPET-WECHAT4U)
02:37:35 VERB MemoryCard save() file: /home/zixia/chatie/wechaty/padchat-demo.memory-card.json
```

**Comment by pangxie231** [comment]
I also encountered the same problem

**Comment by 951871040** [comment]
这个库是不是停更了？
