### ISSUE TITLE
登录成功之后，报错

### ISSUE THREAD

**Issue by sinajia** [Chatie/wechaty-puppet-wechat4u#55]
2023-04-25 21:54: 21:54:24 WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
2023-04-25 21:54: AssertionError [ERR_ASSERTION]: 1205 == 0
2023-04-25 21:54:     at Object.equal (/yj/prj/wechatbot/node_modules/wechat4u/lib/util/global.js:69:24)
2023-04-25 21:54:     at /yj/prj/wechatbot/node_modules/wechat4u/lib/core.js:324:24
2023-04-25 21:54:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-04-25 21:54:     at async Promise.all (index 1) {
2023-04-25 21:54:   code: 2,
2023-04-25 21:54:   details: 'AssertionError [ERR_ASSERTION]: 1205 == 0\n' +
2023-04-25 21:54:     '    at Object.equal (/yj/prj/wechatbot/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
2023-04-25 21:54:     '    at /yj/prj/wechatbot/node_modules/wechat4u/lib/core.js:324:24\n' +
2023-04-25 21:54:     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
2023-04-25 21:54:     '    at async Promise.all (index 1)'
2023-04-25 21:54: }

**Comment by sinajia** [comment]
看了一下代码，是warn提示，这个warn可以如下修改去掉
```js
process.env['WECHATY_LOG'] = 'error';
(async () => {
  await import('./src/wechaty/index.js');
})();
```
将入口文件后缀改为cjs，暂时可以去掉
