### ISSUE TITLE
最新版只能发送文本 can't send messages other than simple text

### ISSUE THREAD

**Issue by revintec** [Chatie/wechaty-puppet-wechat4u#76]
Hi, thanks for the great project in advance
I'm using `wechaty 1.20.2`, installed through `npm install wechaty`
it includes `wechaty-puppet-wechat4u 1.14.13`
both are the latest versions as of writing

1. I wanna send/forward mini-programs, can't find a working doc. neither constructing a new MiniProgram(`async messageSendMiniProgram` is not implemented) nor send/forwarding existing one works
https://github.com/wechaty/puppet-wechat4u/blob/b9a21f0b985b69810a909bdafdd2bdef54e38d0e/src/puppet-wechat4u.ts#L831-L837
2. I've switched to different puppets, but it seems only wechat4u(the default) works on linux, is that true?
3. I've tried different accounts, it seems the problem is not caused by Tencent server blocking

先感谢下这个项目，期待项目调通后资助
通过官网提供的`npm install wechaty`安装了最新版
wechaty 1.20.2, wechaty-puppet-wechat4u 1.14.13
无法发送除文本以外的内容
1. 按文档中的方法无法发送、转发小程序，用构造函数（看了下代码`async messageSendMiniProgram`没实现，英文描述有链接）和调用say，forward都不行。求一个可用的例子
2. 在linux上，只有默认的wechat4u可用么？我切换到其他的都有各种报错
3. 试了不同的账号都不行，应该不是新账号被腾讯阻断的原因
代码和日志如下：

here is the reference code: `bot.js`
```javascript
import { WechatyBuilder } from "wechaty"
import qrTerm from "qrcode-terminal"
import fetch from "node-fetch"

WechatyBuilder.build({name:"meow"}).on("scan",(qrcode,status)=>qrTerm.generate(qrcode,{small:true})).on("message",async function(message){
  let target=this.Room.findAll({topic:/社区小助手测试群/})
  target=(await target)[0]
  console.log(message)
  target.say(message)
  message.forward(target);
}).start()
```

when forwarding contact card
```
WechatifiedMessageImpl {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '7407748398598513524',
  payload: {
    id: '7407748398598513524',
    talkerId: '@01c10938222d19d0ef640a23f6373f9ceaab5ff908d7193d49c67410f8241442',
    text: '<?xml version="1.0"?>\n' +
      '<msg bigheadimgurl="http://wx.qlogo.cn/mmhead/Q3auHgzwzM6TFUHia2EgfYsLzp9LeuBs2WeG19ribkiadmAOOuibUceSfg/0" smallheadimgurl="http://wx.qlogo.cn/mmhead/Q3auHgzwzM6TFUHia2EgfYsLzp9LeuBs2WeG19ribkiadmAOOuibUceSfg/132" username="gh_2dafa7fb8e12" nickname="家邻"  shortpy="" alias="" imagestatus="3" scene="17" province="北京" city="中国大陆" sign="" sex="0" certflag="24" certinfo="北京家邻科技有限公司" brandIconUrl="http://mmbiz.qpic.cn/mmbiz_png/ibVRn01rfBwU1PUeUiciawGiayZmz08IRUPX9Nwk3ic7XUiar0athkndS3ldG3C9OO4dDicZH2ibzRyibInXebKJpl6JEJQ/0?wx_fmt=png" brandHomeUrl="" brandSubscriptConfigUrl="{&amp;quot;urls&amp;quot;:[{&amp;quot;title&amp;quot;:&amp;quot;查看历史消息&amp;quot;,&amp;quot;url&amp;quot;:&amp;quot;http:\\/\\/mp.weixin.qq.com\\/mp\\/getmasssendmsg?__biz=MzkzNzI4MzYyOA==#wechat_webview_type=1&amp;amp;wechat_redirect&amp;quot;,&amp;quot;title_key&amp;quot;:&amp;quot;__mp_wording__brandinfo_history_massmsg&amp;quot;}]}" brandFlags="0" regionCode="CN_Beijing_Pinggu" biznamecardinfo="CkhDZ2JscnJicGdyc1FHQm9BSWdFeEtQR0ZvYkFHTWc5bmFGOHlaR0ZtWVRkbVlqaGxNVEk2RERGU1ZrMU1NWFpETjBOWFF3PT0SeEFBZm1QY3dFQUFBQkFBQUFBQUFEOHo2NDI5bHdBYlFrOFVJSVppQUFBQUJ0RU5zTk9RK0MyNDVkMnBxS05QQlFmUWpVd09kdE5SQmhYc005eE90YTFnVXNGOXhDRW5wVVVwNlU5emhUczliYVFVTEVqcHB1VjQ3UA==" />\n',
    timestamp: 1711820479,
    type: 3,
    roomId: '@@1f09e0f64dcc5deea21807893bbde8895e534a81b0b5ddd36e44e3161748f625',
    mentionIdList: []
  },
  [Symbol(kCapture)]: false
}
01:41:20 ERR Message forward(Room<社区小助手测试群>) exception: Error: 该消息类型不能直接转发
uncaughtException Error: 该消息类型不能直接转发
    at /data01/revin/code/wechaty/node_modules/wechat4u/lib/core.js:1020:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:658:9)
    at async WechatifiedUserClass.forward (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/user-modules/message.js:754:27) {
  tips: '转发消息失败'
}
uncaughtException Error: 该消息类型不能直接转发
    at /data01/revin/code/wechaty/node_modules/wechat4u/lib/core.js:1020:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:658:9)
    at async file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/sayable/deliver-sayable.js:28:17
    at async WechatifiedUserClass.say (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/user-modules/room.js:371:21) {
  tips: '转发消息失败'
}
```

when forwarding url link
```
WechatifiedMessageImpl {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '1730824252606489292',
  payload: {
    id: '1730824252606489292',
    talkerId: '@01c10938222d19d0ef640a23f6373f9ceaab5ff908d7193d49c67410f8241442',
    text: '<?xml version="1.0"?>\n' +
      '<msg>\n' +
      '\t<appmsg appid="" sdkver="0">\n' +
      '\t\t<title>商业产品与用户产品的五大区别</title>\n' +
      '\t\t<des>这次的话题要从浅入深地好好聊聊商业产品与用户产品的五大区别~</des>\n' +
      '\t\t<type>5</type>\n' +
      '\t\t<url>http://mp.weixin.qq.com/s?__biz=MzAxNzQxODM1Ng==&amp;amp;mid=2652415214&amp;amp;idx=1&amp;amp;sn=f8d164014d54f8cc361dc862e269cafa&amp;amp;chksm=8009d5f5b77e5ce333a30d8a1fa21993537ffd4cfaa59b87253ca9243e0588c9fe8c72e620c6&amp;amp;mpshare=1&amp;amp;scene=1&amp;amp;srcid=0331qzRrWpNCAJlU1hF8Pt7k&amp;amp;sharer_shareinfo=761ea7f32d1d5a2f54994dff5237963e&amp;amp;sharer_shareinfo_first=761ea7f32d1d5a2f54994dff5237963e#rd</url>\n' +
      '\t\t<appattach>\n' +
      '\t\t\t<cdnthumburl>3052020100044b3049020100020445c8a4e502033d11fe020440f40399020466084c29042462386363383336642d663135652d346331322d383736622d3064613034643530323262610204052408030201000400</cdnthumburl>\n' +
      '\t\t\t<cdnthumbmd5>9669b0a82f8353e4296811790f403817</cdnthumbmd5>\n' +
      '\t\t\t<cdnthumblength>10338</cdnthumblength>\n' +
      '\t\t\t<cdnthumbwidth>296</cdnthumbwidth>\n' +
      '\t\t\t<cdnthumbheight>160</cdnthumbheight>\n' +
      '\t\t\t<cdnthumbaeskey>c598d3aeba71a22c3b082aba4add9240</cdnthumbaeskey>\n' +
      '\t\t\t<aeskey>c598d3aeba71a22c3b082aba4add9240</aeskey>\n' +
      '\t\t\t<encryver>0</encryver>\n' +
      '\t\t\t<filekey>38809399095@chatroom_49_1711820688</filekey>\n' +
      '\t\t</appattach>\n' +
      '\t\t<sourceusername></sourceusername>\n' +
      '\t\t<sourcedisplayname>奇奇的奋斗</sourcedisplayname>\n' +
      '\t\t<md5>9669b0a82f8353e4296811790f403817</md5>\n' +
      '\t\t<mpsharetrace>\n' +
      '\t\t\t<hasfinderelement>0</hasfinderelement>\n' +
      '\t\t\t<lastgmsgid><![CDATA[ChN3eGlkXzlvczJzMHkwYjh6cTIyEhQzODgwOTM5OTA5NUBjaGF0cm9vbSITNDM2MjcxNzYxNDU0NjU4OTg4Mw==]]></lastgmsgid>\n' +
      '\t\t</mpsharetrace>\n' +
      '\t\t<mmreadershare>\n' +
      '\t\t\t<itemshowtype>0</itemshowtype>\n' +
      '\t\t\t<nativepage>0</nativepage>\n' +
      '\t\t\t<pubtime>0</pubtime>\n' +
      '\t\t\t<duration>0</duration>\n' +
      '\t\t\t<width>0</width>\n' +
      '\t\t\t<height>0</height>\n' +
      '\t\t\t<vid />\n' +
      '\t\t\t<funcflag>0</funcflag>\n' +
      '\t\t\t<ispaysubscribe>0</ispaysubscribe>\n' +
      '\t\t</mmreadershare>\n' +
      '\t</appmsg>\n' +
      '\t<fromusername></fromusername>\n' +
      '\t<scene>0</scene>\n' +
      '\t<appinfo>\n' +
      '\t\t<version>1</version>\n' +
      '\t\t<appname></appname>\n' +
      '\t</appinfo>\n' +
      '\t<commenturl></commenturl>\n' +
      '</msg>\n',
    timestamp: 1711820688,
    type: 14,
    roomId: '@@1f09e0f64dcc5deea21807893bbde8895e534a81b0b5ddd36e44e3161748f625',
    mentionIdList: []
  },
  [Symbol(kCapture)]: false
}
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/data01/revin/code/wechaty/node_modules/wechat4u/lib/util/global.js:69:24)
    at /data01/revin/code/wechaty/node_modules/wechat4u/lib/core.js:1029:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:658:9)
    at async file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/sayable/deliver-sayable.js:28:17
    at async WechatifiedUserClass.say (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/user-modules/room.js:371:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '转发消息失败'
}
01:44:49 ERR Message forward(Room<社区小助手测试群>) exception: AssertionError [ERR_ASSERTION]: 1 == 0
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/data01/revin/code/wechaty/node_modules/wechat4u/lib/util/global.js:69:24)
    at /data01/revin/code/wechaty/node_modules/wechat4u/lib/core.js:1029:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:658:9)
    at async WechatifiedUserClass.forward (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/user-modules/message.js:754:27) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '转发消息失败'
}
```

when forwarding mini program
```
WechatifiedMessageImpl {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '8623750724161432741',
  payload: {
    id: '8623750724161432741',
    talkerId: '@01c10938222d19d0ef640a23f6373f9ceaab5ff908d7193d49c67410f8241442',
    text: '<?xml version="1.0"?>\n' +
      '<msg>\n' +
      '\t<appmsg appid="" sdkver="0">\n' +
      '\t\t<title>Hi，这是小区邻居 qin🐠kaixin💋发布的一套直租房源，在 融泽嘉园小区，快来看看吧～</title>\n' +
      '\t\t<des>家邻丨小区租房与邻居都在这儿</des>\n' +
      '\t\t<type>33</type>\n' +
      '\t\t<action>view</action>\n' +
      '\t\t<url>https://mp.weixin.qq.com/mp/waerrpage?appid=wx19e04f0275c29787&amp;amp;type=upgrade&amp;amp;upgradetype=3#wechat_redirect</url>\n' +
      '\t\t<appattach>\n' +
      '\t\t\t<cdnthumburl>3052020100044b3049020100020449af012702033d11fe0204a5f765b402046607e98c042464393064656161362d336535372d343036372d613162642d3730396435366634623866640204051408030201000400</cdnthumburl>\n' +
      '\t\t\t<cdnthumbmd5>b69b55425a59461710cb18bca7b8d02d</cdnthumbmd5>\n' +
      '\t\t\t<cdnthumblength>130978</cdnthumblength>\n' +
      '\t\t\t<cdnthumbwidth>720</cdnthumbwidth>\n' +
      '\t\t\t<cdnthumbheight>576</cdnthumbheight>\n' +
      '\t\t\t<cdnthumbaeskey>54eb35aa80a67f7a876cbb9555e6a39f</cdnthumbaeskey>\n' +
      '\t\t\t<aeskey>54eb35aa80a67f7a876cbb9555e6a39f</aeskey>\n' +
      '\t\t\t<encryver>0</encryver>\n' +
      '\t\t\t<filekey>38809399095@chatroom_50_1711820726</filekey>\n' +
      '\t\t</appattach>\n' +
      '\t\t<sourceusername></sourceusername>\n' +
      '\t\t<sourcedisplayname>家邻丨小区租房与邻居都在这儿</sourcedisplayname>\n' +
      '\t\t<md5>b69b55425a59461710cb18bca7b8d02d</md5>\n' +
      '\t\t<webviewshared>\n' +
      '\t\t\t<jsAppId><![CDATA[]]></jsAppId>\n' +
      '\t\t</webviewshared>\n' +
      '\t\t<mpsharetrace>\n' +
      '\t\t\t<hasfinderelement>0</hasfinderelement>\n' +
      '\t\t</mpsharetrace>\n' +
      '\t\t<weappinfo>\n' +
      '\t\t\t<username></username>\n' +
      '\t\t\t<appid><![CDATA[wx19e04f0275c29787]]></appid>\n' +
      '\t\t\t<type>2</type>\n' +
      '\t\t\t<version>4</version>\n' +
      '\t\t\t<weappiconurl><![CDATA[http://mmbiz.qpic.cn/mmbiz_png/4RVfKMSwJibj5UWofFMqSPyLIQqmH2D75eV5SaYp9Mr9PHiamibUKWfMxAS2qO46q98d7bWv38PU4IzUZqKIvcIQg/640?wx_fmt=png&amp;wxfrom=200]]></weappiconurl>\n' +
      '\t\t\t<pagepath><![CDATA[pkgMain/house/index.html?houseId=562]]></pagepath>\n' +
      '\t\t\t<shareId><![CDATA[0_wx19e04f0275c29787_987152fe53a6993fd3b3b58f518a76ef_1711788990_0]]></shareId>\n' +
      '\t\t\t<appservicetype>0</appservicetype>\n' +
      '\t\t\t<brandofficialflag>0</brandofficialflag>\n' +
      '\t\t\t<showRelievedBuyFlag>0</showRelievedBuyFlag>\n' +
      '\t\t\t<hasRelievedBuyPlugin>0</hasRelievedBuyPlugin>\n' +
      '\t\t\t<flagshipflag>0</flagshipflag>\n' +
      '\t\t\t<subType>0</subType>\n' +
      '\t\t\t<videopageinfo>\n' +
      '\t\t\t\t<thumbwidth>720</thumbwidth>\n' +
      '\t\t\t\t<thumbheight>576</thumbheight>\n' +
      '\t\t\t\t<videosource><![CDATA[]]></videosource>\n' +
      '\t\t\t\t<fromopensdk>0</fromopensdk>\n' +
      '\t\t\t\t<appthumburl><![CDATA[(null)]]></appthumburl>\n' +
      '\t\t\t</videopageinfo>\n' +
      '\t\t\t<isprivatemessage>0</isprivatemessage>\n' +
      '\t\t</weappinfo>\n' +
      '\t\t<secretmsg>\n' +
      '\t\t\t<isscrectmsg>0</isscrectmsg>\n' +
      '\t\t</secretmsg>\n' +
      '\t</appmsg>\n' +
      '\t<fromusername></fromusername>\n' +
      '\t<scene>0</scene>\n' +
      '\t<appinfo>\n' +
      '\t\t<version>1</version>\n' +
      '\t\t<appname></appname>\n' +
      '\t</appinfo>\n' +
      '\t<commenturl></commenturl>\n' +
      '</msg>\n',
    timestamp: 1711820726,
    type: 9,
    roomId: '@@1f09e0f64dcc5deea21807893bbde8895e534a81b0b5ddd36e44e3161748f625',
    mentionIdList: []
  },
  [Symbol(kCapture)]: false
}
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/data01/revin/code/wechaty/node_modules/wechat4u/lib/util/global.js:69:24)
    at /data01/revin/code/wechaty/node_modules/wechat4u/lib/core.js:1029:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:658:9)
    at async file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/sayable/deliver-sayable.js:28:17
    at async WechatifiedUserClass.say (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/user-modules/room.js:371:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '转发消息失败'
}
01:45:27 ERR Message forward(Room<社区小助手测试群>) exception: AssertionError [ERR_ASSERTION]: 1 == 0
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/data01/revin/code/wechaty/node_modules/wechat4u/lib/util/global.js:69:24)
    at /data01/revin/code/wechaty/node_modules/wechat4u/lib/core.js:1029:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:658:9)
    at async WechatifiedUserClass.forward (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/user-modules/message.js:754:27) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '转发消息失败'
}
```

**Comment by leochen-g** [comment]
网页版微信本身就不支持小程序的发送，所以项目也无法实现网页版微信无法实现的功能

**Comment by revintec** [comment]
> 网页版微信本身就不支持小程序的发送，所以项目也无法实现网页版微信无法实现的功能


@leochen-g 感谢感谢

1. 那需要切到哪个puppet才支持发送呢？我可以在macos和/或linux上跑服务
2. 除了小程序，UrlLink也发不出去，这个符合预期嘛？

---
1. 我看了文档里说的，但没有找到macpro的puppet的文档，npm也无法安装。不过源代码里的注释没有提及必须用macpro
https://wechaty.js.org/docs/api/room#roomsaytext-or-contact-or-file-or-urllink-or-miniprogram-mentionlist--promise-void:~:text=wechaty-puppet-macpro
<img width="961" alt="image" src="https://github.com/wechaty/puppet-wechat4u/assets/8952734/2f557c47-056d-4d3c-9ae4-fe353a903f56">

```
npm install wechaty-puppet-macpro
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: wechaty@1.0.0
npm ERR! Found: wechaty-puppet@1.20.2
npm ERR! node_modules/wechaty-puppet
npm ERR!   wechaty-puppet@"^1.20.1" from wechaty@1.20.2
npm ERR!   node_modules/wechaty
npm ERR!     peer wechaty@"^1.18.1" from wechaty-redux@1.20.2
npm ERR!     node_modules/wechaty-redux
npm ERR!       wechaty-redux@"^1.20.2" from wechaty-puppet-service@1.19.9
npm ERR!       node_modules/wechaty-puppet-service
npm ERR!         wechaty-puppet-service@"^1.19.8" from wechaty@1.20.2
npm ERR!     wechaty@"^1.20.2" from the root project
npm ERR!   peer wechaty-puppet@"^1.19.1" from wechaty-puppet-service@1.19.9
npm ERR!   node_modules/wechaty-puppet-service
npm ERR!     wechaty-puppet-service@"^1.19.8" from wechaty@1.20.2
npm ERR!   3 more (wechaty-puppet-wechat, wechaty-puppet-wechat4u, wechaty-redux)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! wechaty-puppet-macpro@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: wechaty-puppet@0.24.0
npm ERR! node_modules/wechaty-puppet
npm ERR!   peer wechaty-puppet@"^0.24.0" from wechaty-puppet-macpro@0.6.0
npm ERR!   node_modules/wechaty-puppet-macpro
npm ERR!     wechaty-puppet-macpro@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /data01/revin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data01/revin/.npm/_logs/2024-03-31T09_19_30_091Z-debug.log
Process exited with status code 1
```
2. puppet文档页有点没看懂，里面我挑了几个看起来有前途的puppet，似乎也安装不上（它们依赖的wechaty比较低好像是0.x版本的
https://wechaty.js.org/zh/docs/puppet-providers/
3. wechaty-puppet-wechat 似乎也是web，所以可能也不能转发小程序？（以下是环境配置问题，如果确认它也不能发小程序，那我就先不折腾修复这个环境问题了

```
17:13:54 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:266:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:148:13)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:45:26)
    at PuppetWeChat.<anonymous> (file:///data01/revin/code/wechaty/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:155:34)
    at PuppetWeChat.emit (node:events:390:28)
    at PuppetWeChat.emit (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:107:22)
    at Bridge.<anonymous> (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:168:45)
    at Bridge.emit (node:events:390:28)
    at file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:37:42
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:266:23)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.onLoad (file:///data01/revin/code/wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:148:13)'
}
Process exited with status code 1
```
4. `wechaty-puppet-padpro`等其他puppet似乎也有各种问题。。。

**Comment by leochen-g** [comment]
https://github.com/wechaty/puppet-padlocal

**Comment by aqpmzngldh** [comment]
> https://github.com/wechaty/puppet-padlocal

这个一个月200撑不住
