### ISSUE TITLE
puppet-mixin.js  puppet.on('room-join' xxx    playload missing [inviteeIdList] property 

### ISSUE THREAD

**Issue by pangchia** [Chatie/wechaty-puppet-wechat4u#85]
![20240817223022](https://github.com/user-attachments/assets/7472e7a4-b57f-4c82-8eb5-d787def330a6)

---
{"inviteeIdList":[null],"inviterId":"@f442ed84baa484f36f8e0c533cdd99487a3988d513f6e46585bba40ba079dd12","roomId":"@@e5958527250499b1cb56280647c811a62d0fa372b310fc297a132b21d4486f85","timestamp":1723902388}

---
inviteeIdList is null ,occur under error :

uncaughtException GError: query must provide at least one key. current query is empty.                                                                             
    at PuppetWechat4u.contactQueryFilterFactory (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:117:23)
    at PuppetWechat4u.contactSearch (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:64:41)             
    at async WechatifiedContactImpl.findAll (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty/dist/esm/src/user-modules/contact.js:129:35)           
    at async WechatifiedContactImpl.find (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty/dist/esm/src/user-modules/contact.js:84:29)               
    at async Promise.all (index 0)
    at async PuppetWechat4u.<anonymous> (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:273:56) {
  code: 2,
  details: 'Error: query must provide at least one key. current query is empty.\n' +
    '    at PuppetWechat4u.contactQueryFilterFactory (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:117:23)\n' +
    '    at PuppetWechat4u.contactSearch (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:64:41)\n' +
    '    at async WechatifiedContactImpl.findAll (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty/dist/esm/src/user-modules/contact.js:129:35)\n' +
    '    at async WechatifiedContactImpl.find (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty/dist/esm/src/user-modules/contact.js:84:29)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async PuppetWechat4u.<anonymous> (file:///E:/abc/git/smc-wechaty-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:273:56)'

**Comment by pangchia** [comment]
wechaty   1.20.2
wechaty-puppet-wechat4u  1.14.14

**Comment by zhangjiana** [comment]
需要在这里判断下是否为空inviteeIdList。
下面是我的解决方法。在源码里面改的。
![image](https://github.com/user-attachments/assets/2fefb987-b617-4d83-9903-be9af24e5369)
