### ISSUE TITLE
最近突然不能用了，报错信息如下，之前还一直用着，现在是在不同电脑上启动都失败了，二维码也不显示了...

### ISSUE THREAD

**Issue by qjhe** [Chatie/wechaty-puppet-wechat4u#86]
uncaughtException AssertionError [ERR_ASSERTION]: 1102 == 0
    at Object.equal (/Users/i2share-qjh/test/wchat/node_modules/wechat4u/lib/util/global.js:69:24)
    at /Users/i2share-qjh/test/wchat/node_modules/wechat4u/lib/core.js:227:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1102 == 0\n' +
    '    at Object.equal (/Users/i2share-qjh/test/wchat/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /Users/i2share-qjh/test/wchat/node_modules/wechat4u/lib/core.js:227:24\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by FreeManFJ** [comment]
我也遇到了，把card.json删掉就可以重新扫码登录，不知道怎么解决。
并且我这边一到凌晨12点就会自动下线
