### ISSUE TITLE
发送文件失败

### ISSUE THREAD

**Issue by KaneOne** [Chatie/wechaty-puppet-wechat4u#87]
昨天还可以发送，今天就不行了。
```
2024-09-13 17:09:22.830 ERROR 9364 AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (/root/project/iop/wechat-bot/node_modules/.pnpm/wechat4u@0.7.14/node_modules/wechat4u/src/util/global.js:53:14)
    at /root/project/iop/wechat-bot/node_modules/.pnpm/wechat4u@0.7.14/node_modules/wechat4u/src/core.js:859:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PuppetWechat4u.messageSendFile (/root/project/iop/wechat-bot/node_modules/.pnpm/wechaty-puppet-wechat4u@1.14.14_@swc+core@1.7.23_wechaty-puppet@1.20.2_debug@4.3.5_rxjs@7.8.1_/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:813:5)
    at /root/project/iop/wechat-bot/node_modules/.pnpm/wechaty@1.20.2_@swc+core@1.7.23_brolog@1.14.2_debug@4.3.5_redux@4.2.1_rxjs@7.8.1/node_modules/wechaty/src/sayable/deliver-sayable.ts:41:13
    at WechatifiedUserClass.say (/root/project/iop/wechat-bot/node_modules/.pnpm/wechaty@1.20.2_@swc+core@1.7.23_brolog@1.14.2_debug@4.3.5_redux@4.2.1_rxjs@7.8.1/node_modules/wechaty/src/user-modules/contact.ts:338:19)
    at WechatyService.sendMessage (/root/project/iop/wechat-bot/src/service/wechaty/wechaty.service.ts:160:7)
    at SendPolicyFileProcessor.execute (/root/project/iop/wechat-bot/src/queue/wechat.queue.ts:22:9)
    at /root/project/iop/wechat-bot/node_modules/.pnpm/@midwayjs+bull@3.17.1/node_modules/@midwayjs/bull/dist/framework.js:115:28
    at /root/project/iop/wechat-bot/node_modules/.pnpm/@midwayjs+core@3.16.2/node_modules/@midwayjs/core/dist/baseFramework.js:273:40 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: -1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文件失败'
}
```

**Comment by KaneOne** [comment]
好像因为好友没有找到的原因。
